version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_data_project
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - data_network
    command: --default-authentication-plugin=mysql_native_password

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_data_project
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - data_network

volumes:
  mysql_data:

networks:
  data_network:
